## **Assignment Task 01**

In [ ]:
import numpy as np

def print_matrix(matrix):
    for row in matrix:
        print(row)

def row_rotation(exam_week, seat_status) :
  rows = len(seat_status)
  cols = len(seat_status[0])
  turns = (exam_week -1) % rows

  for i in range(turns) :
    last_col = [0] * cols
    for j in range(cols) :
      last_col[j] = seat_status[rows - 1][j]


    for i in range(rows-1,0,-1) :
      for j in range(cols) :
        seat_status[i][j] = seat_status[i-1][j]


    for j in range(cols) :
      seat_status[0][j] = last_col[j]

  row_number = -1
  for i in range(rows):
      for j in range(cols):
          if seat_status[i][j] == "AA":
              row_number = i + 1
              break


  print_matrix(seat_status)
  print()

  return row_number

seat_status = np.array([[ 'A' , 'B' , 'C' , 'D' , 'E'],
                  ['F' , 'G' , 'H' , 'I' , 'J'],
                  ['K' , 'L' , 'M' , 'N' , 'O'],
                  ['P' , 'Q' , 'R' , 'S' , 'T'],
                  ['U' , 'V' , 'W' , 'X' , 'Y'],
                  ['Z' , 'AA' , 'BB' , 'CC' , 'DD']])
exam_week=3
print()

row_number=row_rotation(exam_week, seat_status)
print(f'Your friend AA will be on row {row_number}')


['U' 'V' 'W' 'X' 'Y']
['Z' 'AA' 'BB' 'CC' 'DD']
['A' 'B' 'C' 'D' 'E']
['F' 'G' 'H' 'I' 'J']
['K' 'L' 'M' 'N' 'O']
['P' 'Q' 'R' 'S' 'T']

Your friend AA will be on row 2


## **Assignment Task 02**

In [6]:
import numpy as np

def print_matrix(matrix):
    for row in matrix:
        print(row)

def compressed_matrix(mat) :
  rows = len(mat)
  cols = len(mat[0])

  new_rows = rows // 2
  new_cols = cols // 2

  compressed_mat = np.zeros((new_rows, new_cols), dtype=int)

  for i in range(new_rows) :
    for j in range(new_cols) :

      total = 0
      for r in range(i*new_rows, (i+1)*new_rows) :
        for c in range(j*new_cols, (j+1)*new_cols) :
          total += mat[r][c]

      compressed_mat[i][j] = total


  return compressed_mat

matrix=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [1,3,5,2],
                 [-2,0,6,-3]
                 ])
print_matrix(matrix)
print("\n..............................\n")
returned_array=compressed_matrix(matrix)
print_matrix(returned_array)

[1 2 3 4]
[5 6 7 8]
[1 3 5 2]
[-2  0  6 -3]

..............................

[14 22]
[ 2 10]


### **Aissgnment 03**

In [ ]:
import numpy as np

def play_game(mat) :
  rows = len(mat)
  cols = len(mat[0])
  d = [(-1, 0), (1, 0), (0, -1), (0, 1)]
  total = 0

  for i in range(rows) :
    for j in range(cols) :
      if(mat[i][j] % 50 == 0 and mat[i][j] != 0) :
        points = 0
        for dx,dy in (d) :
          ni = i + dx
          nj = j + dy
          if(ni >= 0 and ni < rows and nj >= 0 and nj < cols) :
            if(mat[ni][nj]==2) :
              points += 2

        total += points

  if total >= 10:
        print(f"Points Gained: {total}. Your team has survived the game.")
  else:
        print(f"Points Gained: {total}. Your team is out.")



matrix1 = [
    [0, 2, 2, 0],
    [50, 1, 2, 0],
    [2, 2, 2, 0],
    [1, 100, 2, 0]
]

matrix2 = [
    [0, 2, 2, 0, 2],
    [1, 50, 2, 1, 100],
    [2, 2, 2, 0, 2],
    [0, 200, 2, 0, 0]
]

play_game(matrix1)

play_game(matrix2)

Points Gained: 6. Your team is out.
Points Gained: 14. Your team has survived the game.


### **Assignment 04**

In [5]:
import numpy as np

def rotate_matrix(matrix, layer, rotations):
    n = len(matrix)
    start = layer
    end = n - 1 - layer

    for _ in range(rotations):
        prev = matrix[start][start]

        for j in range(start + 1, end + 1):
            temp = matrix[start][j]
            matrix[start][j] = prev
            prev = temp

        for i in range(start + 1, end + 1):
            temp = matrix[i][end]
            matrix[i][end] = prev
            prev = temp

        for j in range(end - 1, start - 1, -1):
            temp = matrix[end][j]
            matrix[end][j] = prev
            prev = temp

        for i in range(end - 1, start - 1, -1):
            temp = matrix[i][start]
            matrix[i][start] = prev
            prev = temp


def rotate_secret(matrix):
    layers = len(matrix) // 2
    for layer in range(layers):
        rotations = layer + 1
        rotate_matrix(matrix, layers - 1 - layer, rotations)

    message = ''.join(''.join(row) for row in matrix)
    print(message)

board1 = [
    ['T','A','U','S'],
    ['A','R','I','.'],
    ['D','T','T','N'],
    ['S','C','F','U']
]

rotate_secret(board1)  # Output: DATASTRUCTISFUN.

# --- Sample Test 2 ---
board2 = [
    ['O','R','I','R','N','P'],
    ['G','S','A','A','L','R'],
    ['L','M','N','O','N','Y'],
    ['A','H','U','O','O','P'],
    ['T','F','C','T','H','S'],
    ['E','D','Y','O','C','K']
]

rotate_secret(board2)  # Output: ALGORITHMSAREFUNANDCOOLPYTHONROCKSPY

DATASTRUCTISFUN.
ALGORITHMSAREFUNANDCOOLPYTHONROCKSPY
